import { Contestant } from "@/src/types";

export const LEADERBOARD_DATA: Contestant[] = [
  {
    id: "1", rank: 1, avatar: "🧑‍💻", name: "Aryan Kapoor", handle: "@aryan.k",
    country: "India", flag: "🇮🇳", university: "IIT Bombay", niScore: 9847, scoreChange: 142,
    categories: ["tech", "research"], tags: ["ML", "Systems", "Open Source"],
    bio: "Full-stack engineer & ML researcher. Published 3 papers on transformer architectures. Building the future one commit at a time.",
    followers: 12400, following: 342, rankPercentile: "Top 0.01%", joinedDate: "Jan 2024",
    skills: [{ label: "Code", value: 98, color: "#1A56FF" }, { label: "Research", value: 94, color: "#00BE6A" }, { label: "Collab", value: 87, color: "#FF4500" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 94, weight: "25%", description: "GPA, coursework, academic awards", color: "#1A56FF", items: ["GPA 3.97/4.0", "Dean's List ×6", "Academic Excellence Award"] },
      { id: "research", name: "Research", icon: "🔬", score: 91, weight: "25%", description: "Papers, citations, contributions", color: "#00BE6A", items: ["3 Published Papers", "47 Citations", "ICLR 2024 Spotlight"] },
      { id: "code", name: "Code", icon: "💻", score: 98, weight: "20%", description: "GitHub activity, open source", color: "#9333EA", items: ["2,847 Contributions", "12 Stars Repos", "Top 1% GitHub"] },
      { id: "creator", name: "Creator", icon: "✨", score: 72, weight: "15%", description: "Content, courses, tutorials", color: "#F5A200", items: ["4 Technical Blogs", "1.2k Followers"] },
      { id: "social", name: "Social", icon: "🤝", score: 83, weight: "15%", description: "Community, mentoring, impact", color: "#FF4500", items: ["Mentor 14 Students", "Hackathon Judge"] },
    ],
    achievements: [
      { id: "a1", icon: "🏆", title: "Google Summer of Code 2024", date: "Jun 2024" },
      { id: "a2", icon: "📄", title: "ICLR 2024 — Spotlight Paper", date: "May 2024" },
      { id: "a3", icon: "🥇", title: "HackMIT 2024 — 1st Place", date: "Sep 2024" },
      { id: "a4", icon: "⭐", title: "GitHub Star Developer", date: "Mar 2024" },
    ],
    socials: [{ platform: "GitHub", handle: "@aryankapoor", url: "#" }, { platform: "LinkedIn", handle: "aryan-kapoor", url: "#" }, { platform: "X", handle: "@aryan_builds", url: "#" }],
  },
  {
    id: "2", rank: 2, avatar: "👩‍🔬", name: "Sofia Martínez", handle: "@sofia.m",
    country: "Spain", flag: "🇪🇸", university: "MIT", niScore: 9621, scoreChange: 89,
    categories: ["research", "tech"], tags: ["BioML", "Drug Discovery", "PhD"],
    bio: "Computational biologist. PhD candidate at MIT. Passionate about using AI to cure disease.",
    followers: 9800, following: 211, rankPercentile: "Top 0.02%", joinedDate: "Feb 2024",
    skills: [{ label: "Research", value: 97, color: "#00BE6A" }, { label: "Code", value: 89, color: "#1A56FF" }, { label: "Writing", value: 92, color: "#9333EA" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 97, weight: "25%", description: "", color: "#1A56FF", items: ["PhD Candidate MIT", "NSF Fellowship", "Summa Cum Laude"] },
      { id: "research", name: "Research", icon: "🔬", score: 96, weight: "25%", description: "", color: "#00BE6A", items: ["8 Published Papers", "124 Citations", "Nature Methods 2024"] },
      { id: "code", name: "Code", icon: "💻", score: 84, weight: "20%", description: "", color: "#9333EA", items: ["1,203 Contributions", "3 OSS Tools"] },
      { id: "creator", name: "Creator", icon: "✨", score: 68, weight: "15%", description: "", color: "#F5A200", items: ["Science Communicator", "TEDx Speaker"] },
      { id: "social", name: "Social", icon: "🤝", score: 79, weight: "15%", description: "", color: "#FF4500", items: ["Women in STEM Mentor", "Lab Lead"] },
    ],
    achievements: [
      { id: "a1", icon: "🏅", title: "NSF Graduate Research Fellowship", date: "Sep 2023" },
      { id: "a2", icon: "📄", title: "Nature Methods Publication", date: "Apr 2024" },
      { id: "a3", icon: "🎤", title: "TEDx MIT Speaker", date: "Nov 2024" },
    ],
    socials: [{ platform: "GitHub", handle: "@sofiamtz", url: "#" }, { platform: "Scholar", handle: "Sofia Martínez", url: "#" }],
  },
  {
    id: "3", rank: 3, avatar: "🎮", name: "Kenji Nakamura", handle: "@kenji.n",
    country: "Japan", flag: "🇯🇵", university: "Tokyo University", niScore: 9388, scoreChange: -23,
    categories: ["gaming", "tech"], tags: ["Competitive Prog", "Game Dev", "Algorithms"],
    bio: "Competitive programmer & game developer. Two-time ICPC World Finalist. Building indie games on the side.",
    followers: 7200, following: 178, rankPercentile: "Top 0.05%", joinedDate: "Mar 2024",
    skills: [{ label: "Algorithms", value: 99, color: "#1A56FF" }, { label: "Code", value: 96, color: "#9333EA" }, { label: "Design", value: 71, color: "#F5A200" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 88, weight: "25%", description: "", color: "#1A56FF", items: ["GPA 3.9/4.0", "CS Olympiad Gold"] },
      { id: "research", name: "Research", icon: "🔬", score: 72, weight: "25%", description: "", color: "#00BE6A", items: ["2 Conference Papers", "15 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 99, weight: "20%", description: "", color: "#9333EA", items: ["ICPC 2-time Finalist", "LeetCode Top 50", "Codeforces 3200+"] },
      { id: "creator", name: "Creator", icon: "✨", score: 81, weight: "15%", description: "", color: "#F5A200", items: ["Indie Game Dev", "15k Steam Wishlist"] },
      { id: "social", name: "Social", icon: "🤝", score: 74, weight: "15%", description: "", color: "#FF4500", items: ["CP Community Lead", "Algorithm Tutor"] },
    ],
    achievements: [
      { id: "a1", icon: "🏆", title: "ICPC World Finals 2024 — 2nd Place", date: "Apr 2024" },
      { id: "a2", icon: "🎮", title: "Steam Game — 15k Wishlists", date: "Jan 2024" },
      { id: "a3", icon: "⭐", title: "Codeforces Grandmaster", date: "Feb 2024" },
    ],
    socials: [{ platform: "GitHub", handle: "@kenjin", url: "#" }, { platform: "X", handle: "@kenji_cp", url: "#" }],
  },
  {
    id: "4", rank: 4, avatar: "🎨", name: "Amara Osei", handle: "@amara.o",
    country: "Ghana", flag: "🇬🇭", university: "Ashesi University", niScore: 9104, scoreChange: 201,
    categories: ["creative", "social"], tags: ["UX", "Design Systems", "Accessibility"],
    bio: "UX designer & design systems lead. Creating accessible products for 1B+ users across Africa.",
    followers: 18900, following: 423, rankPercentile: "Top 0.08%", joinedDate: "Jan 2024",
    skills: [{ label: "Design", value: 98, color: "#F5A200" }, { label: "UX", value: 95, color: "#9333EA" }, { label: "Code", value: 72, color: "#1A56FF" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 83, weight: "25%", description: "", color: "#1A56FF", items: ["GPA 3.8/4.0", "Design Excellence Award"] },
      { id: "research", name: "Research", icon: "🔬", score: 65, weight: "25%", description: "", color: "#00BE6A", items: ["UX Research Lead", "CHI Workshop 2024"] },
      { id: "code", name: "Code", icon: "💻", score: 71, weight: "20%", description: "", color: "#9333EA", items: ["Open Design System", "React Component Lib"] },
      { id: "creator", name: "Creator", icon: "✨", score: 98, weight: "15%", description: "", color: "#F5A200", items: ["18k Followers", "Design Newsletter 10k+", "Dribbble Top Shot"] },
      { id: "social", name: "Social", icon: "🤝", score: 95, weight: "15%", description: "", color: "#FF4500", items: ["Africa Design Lead", "Mentor 40+ Designers"] },
    ],
    achievements: [
      { id: "a1", icon: "🏅", title: "Google UX Design Residency", date: "Jul 2024" },
      { id: "a2", icon: "🎨", title: "Awwwards Site of the Year", date: "Dec 2024" },
      { id: "a3", icon: "🌍", title: "Forbes 30 Under 30 Africa", date: "Mar 2024" },
    ],
    socials: [{ platform: "Dribbble", handle: "@amara_ux", url: "#" }, { platform: "LinkedIn", handle: "amara-osei", url: "#" }, { platform: "X", handle: "@amara_designs", url: "#" }],
  },
  {
    id: "5", rank: 5, avatar: "🧬", name: "Lena Volkova", handle: "@lena.v",
    country: "Germany", flag: "🇩🇪", university: "TU Munich", niScore: 8897, scoreChange: 56,
    categories: ["research", "tech"], tags: ["Quantum", "Drug Discovery", "Physics"],
    bio: "Quantum computing researcher. Building fault-tolerant quantum algorithms for drug discovery.",
    followers: 6100, following: 89, rankPercentile: "Top 0.1%", joinedDate: "Apr 2024",
    skills: [{ label: "Research", value: 96, color: "#00BE6A" }, { label: "Math", value: 99, color: "#1A56FF" }, { label: "Code", value: 87, color: "#9333EA" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 96, weight: "25%", description: "", color: "#1A56FF", items: ["PhD Quantum Computing", "DAAD Scholar", "Summa Cum Laude"] },
      { id: "research", name: "Research", icon: "🔬", score: 94, weight: "25%", description: "", color: "#00BE6A", items: ["6 Papers", "89 Citations", "Physical Review Letters"] },
      { id: "code", name: "Code", icon: "💻", score: 85, weight: "20%", description: "", color: "#9333EA", items: ["Qiskit Contributor", "Open Quantum Tools"] },
      { id: "creator", name: "Creator", icon: "✨", score: 61, weight: "15%", description: "", color: "#F5A200", items: ["Quantum YouTube: 8k subs"] },
      { id: "social", name: "Social", icon: "🤝", score: 72, weight: "15%", description: "", color: "#FF4500", items: ["QC Community Organizer", "EuroQuantum Lead"] },
    ],
    achievements: [
      { id: "a1", icon: "⚛️", title: "Physical Review Letters Publication", date: "Aug 2024" },
      { id: "a2", icon: "🏆", title: "IBM Quantum Excellence Award", date: "Oct 2024" },
      { id: "a3", icon: "🎓", title: "DAAD Fellowship", date: "Sep 2023" },
    ],
    socials: [{ platform: "GitHub", handle: "@lenavolkova", url: "#" }, { platform: "Scholar", handle: "Lena Volkova", url: "#" }],
  },
  {
    id: "6", rank: 6, avatar: "🚀", name: "Marcus Chen", handle: "@marcus.c",
    country: "Singapore", flag: "🇸🇬", university: "NUS", niScore: 8743, scoreChange: 118,
    categories: ["tech", "social"], tags: ["Founder", "DevTools", "Startup"],
    bio: "Founder & CTO. Built 3 startups, 2 exits. Now building developer tooling at scale.",
    followers: 22100, following: 567, rankPercentile: "Top 0.12%", joinedDate: "Jan 2024",
    skills: [{ label: "Startup", value: 97, color: "#FF4500" }, { label: "Code", value: 93, color: "#1A56FF" }, { label: "Ops", value: 88, color: "#00BE6A" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 81, weight: "25%", description: "", color: "#1A56FF", items: ["CS Honors NUS", "Start-up Module Lead"] },
      { id: "research", name: "Research", icon: "🔬", score: 58, weight: "25%", description: "", color: "#00BE6A", items: ["1 Industry Paper", "10 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 93, weight: "20%", description: "", color: "#9333EA", items: ["2,100 Contributions", "Popular OSS Projects"] },
      { id: "creator", name: "Creator", icon: "✨", score: 89, weight: "15%", description: "", color: "#F5A200", items: ["22k Followers", "Tech Newsletter 14k"] },
      { id: "social", name: "Social", icon: "🤝", score: 94, weight: "15%", description: "", color: "#FF4500", items: ["2 Startup Exits", "Angel Investor", "Tech Mentor 50+"] },
    ],
    achievements: [
      { id: "a1", icon: "🚀", title: "2x YC-Backed Startup Founder", date: "2023" },
      { id: "a2", icon: "💰", title: "$4M Seed Round Closed", date: "Jun 2024" },
      { id: "a3", icon: "🌏", title: "Forbes Asia 30 Under 30", date: "Jan 2024" },
    ],
    socials: [{ platform: "X", handle: "@marcusbuilds", url: "#" }, { platform: "LinkedIn", handle: "marcus-chen-sg", url: "#" }, { platform: "GitHub", handle: "@marcusc", url: "#" }],
  },
  {
    id: "7", rank: 7, avatar: "📡", name: "Priya Nair", handle: "@priya.n",
    country: "India", flag: "🇮🇳", university: "IISc Bangalore", niScore: 8521, scoreChange: 0,
    categories: ["research", "tech"], tags: ["6G", "Wireless", "IEEE"],
    bio: "Wireless systems researcher. Working on next-gen 6G protocols at IISc.",
    followers: 4300, following: 201, rankPercentile: "Top 0.15%", joinedDate: "May 2024",
    skills: [{ label: "Research", value: 94, color: "#00BE6A" }, { label: "Systems", value: 91, color: "#1A56FF" }, { label: "Math", value: 96, color: "#9333EA" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 95, weight: "25%", description: "", color: "#1A56FF", items: ["PhD IISc", "Prime Minister Research Fellow", "Gold Medal"] },
      { id: "research", name: "Research", icon: "🔬", score: 93, weight: "25%", description: "", color: "#00BE6A", items: ["5 IEEE Papers", "72 Citations", "IEEE Globecom Best Paper"] },
      { id: "code", name: "Code", icon: "💻", score: 79, weight: "20%", description: "", color: "#9333EA", items: ["MATLAB Toolbox OSS", "Python SDR Tools"] },
      { id: "creator", name: "Creator", icon: "✨", score: 55, weight: "15%", description: "", color: "#F5A200", items: ["Technical Blog: 3k readers"] },
      { id: "social", name: "Social", icon: "🤝", score: 71, weight: "15%", description: "", color: "#FF4500", items: ["IEEE Student Lead", "Lab Mentor"] },
    ],
    achievements: [
      { id: "a1", icon: "📡", title: "IEEE Globecom Best Paper Award", date: "Dec 2024" },
      { id: "a2", icon: "🎓", title: "Prime Minister Research Fellowship", date: "Aug 2023" },
      { id: "a3", icon: "🏅", title: "Gold Medal — IISc ECE", date: "May 2023" },
    ],
    socials: [{ platform: "Scholar", handle: "Priya Nair", url: "#" }, { platform: "LinkedIn", handle: "priya-nair-iisc", url: "#" }],
  },
  {
    id: "8", rank: 8, avatar: "🎵", name: "Zara Ahmed", handle: "@zara.a",
    country: "Pakistan", flag: "🇵🇰", university: "LUMS", niScore: 8341, scoreChange: 167,
    categories: ["creative", "tech"], tags: ["Audio ML", "Music Tech", "AI"],
    bio: "Audio ML researcher & music producer. Building AI-powered tools for independent musicians.",
    followers: 14200, following: 389, rankPercentile: "Top 0.18%", joinedDate: "Feb 2024",
    skills: [{ label: "Music AI", value: 95, color: "#9333EA" }, { label: "Code", value: 88, color: "#1A56FF" }, { label: "Create", value: 97, color: "#F5A200" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 86, weight: "25%", description: "", color: "#1A56FF", items: ["CS + Music Dual Degree", "LUMS Merit Scholar"] },
      { id: "research", name: "Research", icon: "🔬", score: 79, weight: "25%", description: "", color: "#00BE6A", items: ["ISMIR 2024 Paper", "31 Citations", "Audio AI Lab"] },
      { id: "code", name: "Code", icon: "💻", score: 88, weight: "20%", description: "", color: "#9333EA", items: ["1,450 Contributions", "Open Source Audio Lib"] },
      { id: "creator", name: "Creator", icon: "✨", score: 97, weight: "15%", description: "", color: "#F5A200", items: ["14k Followers", "3 Released Albums", "Spotify 200k streams"] },
      { id: "social", name: "Social", icon: "🤝", score: 82, weight: "15%", description: "", color: "#FF4500", items: ["South Asia Music Tech Lead", "100+ Mentees"] },
    ],
    achievements: [
      { id: "a1", icon: "🎵", title: "ISMIR 2024 — Best Student Paper", date: "Nov 2024" },
      { id: "a2", icon: "🌟", title: "Spotify AI Lab Fellowship", date: "Jul 2024" },
      { id: "a3", icon: "🏆", title: "MIT Media Lab Collaboration Grant", date: "Jan 2024" },
    ],
    socials: [{ platform: "Spotify", handle: "zara.ahmed.music", url: "#" }, { platform: "GitHub", handle: "@zaraaudio", url: "#" }, { platform: "X", handle: "@zara_sound", url: "#" }],
  },
  {
    id: "9", rank: 9, avatar: "⚡", name: "Noah Okafor", handle: "@noah.o",
    country: "Nigeria", flag: "🇳🇬", university: "University of Lagos", niScore: 8198, scoreChange: 244,
    categories: ["tech", "social"], tags: ["Web3", "DeFi", "Fintech"],
    bio: "Blockchain engineer & Web3 founder. Building decentralized finance infrastructure for Africa.",
    followers: 31000, following: 821, rankPercentile: "Top 0.2%", joinedDate: "Jan 2024",
    skills: [{ label: "Web3", value: 97, color: "#F5A200" }, { label: "Code", value: 94, color: "#1A56FF" }, { label: "Impact", value: 91, color: "#FF4500" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 78, weight: "25%", description: "", color: "#1A56FF", items: ["CS Honors", "Best Final Year Project"] },
      { id: "research", name: "Research", icon: "🔬", score: 61, weight: "25%", description: "", color: "#00BE6A", items: ["2 Blockchain Papers", "18 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 97, weight: "20%", description: "", color: "#9333EA", items: ["Solidity Expert", "DeFi Protocol $2M TVL", "3,100 GitHub Contributions"] },
      { id: "creator", name: "Creator", icon: "✨", score: 87, weight: "15%", description: "", color: "#F5A200", items: ["30k Followers", "Web3 Newsletter 25k"] },
      { id: "social", name: "Social", icon: "🤝", score: 92, weight: "15%", description: "", color: "#FF4500", items: ["Africa Web3 Community Lead", "Built Financial Access for 5k+ users"] },
    ],
    achievements: [
      { id: "a1", icon: "⚡", title: "ETHGlobal Hackathon — 1st Place", date: "Aug 2024" },
      { id: "a2", icon: "🌍", title: "Binance Labs Fellowship", date: "Apr 2024" },
      { id: "a3", icon: "🏆", title: "Africa Blockchain Award", date: "Oct 2024" },
    ],
    socials: [{ platform: "GitHub", handle: "@noahokafor", url: "#" }, { platform: "X", handle: "@noah_web3", url: "#" }, { platform: "LinkedIn", handle: "noah-okafor-ng", url: "#" }],
  },
  {
    id: "10", rank: 10, avatar: "🔭", name: "Elena Petrov", handle: "@elena.p",
    country: "Russia", flag: "🇷🇺", university: "Skoltech", niScore: 8054, scoreChange: 31,
    categories: ["research", "tech"], tags: ["Astrophysics", "Data Science", "Python"],
    bio: "Astrophysicist & data scientist. Analyzing exoplanet data from JWST to find biosignatures.",
    followers: 5600, following: 143, rankPercentile: "Top 0.22%", joinedDate: "Mar 2024",
    skills: [{ label: "Astrophysics", value: 96, color: "#9333EA" }, { label: "Python", value: 93, color: "#1A56FF" }, { label: "Stats", value: 97, color: "#00BE6A" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 95, weight: "25%", description: "", color: "#1A56FF", items: ["PhD Candidate Skoltech", "Yandex Fellowship", "4.0 GPA"] },
      { id: "research", name: "Research", icon: "🔬", score: 90, weight: "25%", description: "", color: "#00BE6A", items: ["4 A&A Papers", "63 Citations", "JWST Science Team"] },
      { id: "code", name: "Code", icon: "💻", score: 87, weight: "20%", description: "", color: "#9333EA", items: ["Astropy Contributor", "Open Exoplanet Catalog"] },
      { id: "creator", name: "Creator", icon: "✨", score: 58, weight: "15%", description: "", color: "#F5A200", items: ["Space Outreach Blog", "Science Communicator"] },
      { id: "social", name: "Social", icon: "🤝", score: 65, weight: "15%", description: "", color: "#FF4500", items: ["Astronomy Club Lead", "Public Lecture Series"] },
    ],
    achievements: [
      { id: "a1", icon: "🔭", title: "JWST Early Release Science Program", date: "Jun 2024" },
      { id: "a2", icon: "🏅", title: "Yandex Fellowship in Data Science", date: "Sep 2023" },
      { id: "a3", icon: "⭐", title: "A&A Research Letter — Cover Feature", date: "Mar 2024" },
    ],
    socials: [{ platform: "Scholar", handle: "Elena Petrov", url: "#" }, { platform: "GitHub", handle: "@elenastars", url: "#" }],
  },
  {
    id: "11", rank: 11, avatar: "🤖", name: "Chen Wei", handle: "@chen.w",
    country: "China", flag: "🇨🇳", university: "Tsinghua", niScore: 7921, scoreChange: 77,
    categories: ["tech", "research"], tags: ["Robotics", "CV", "Autonomous Systems"],
    bio: "Robotics engineer & computer vision researcher. Building autonomous systems that perceive the physical world.",
    followers: 8900, following: 267, rankPercentile: "Top 0.25%", joinedDate: "Feb 2024",
    skills: [{ label: "Robotics", value: 97, color: "#1A56FF" }, { label: "CV", value: 94, color: "#9333EA" }, { label: "Code", value: 92, color: "#00BE6A" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 92, weight: "25%", description: "", color: "#1A56FF", items: ["PhD Tsinghua", "National Scholarship", "Top 1 Graduate"] },
      { id: "research", name: "Research", icon: "🔬", score: 88, weight: "25%", description: "", color: "#00BE6A", items: ["CVPR 2024 Paper", "56 Citations", "IEEE RA-L"] },
      { id: "code", name: "Code", icon: "💻", score: 92, weight: "20%", description: "", color: "#9333EA", items: ["ROS2 Contributor", "2,300 Contributions"] },
      { id: "creator", name: "Creator", icon: "✨", score: 61, weight: "15%", description: "", color: "#F5A200", items: ["Robotics YouTube 12k", "Technical Blog"] },
      { id: "social", name: "Social", icon: "🤝", score: 69, weight: "15%", description: "", color: "#FF4500", items: ["Robotics Lab Mentor", "IEEE RAS Member"] },
    ],
    achievements: [
      { id: "a1", icon: "🤖", title: "CVPR 2024 Best Demo Award", date: "Jun 2024" },
      { id: "a2", icon: "🏆", title: "China Robotics Competition — 1st Place", date: "Nov 2024" },
      { id: "a3", icon: "🎓", title: "National Excellent Thesis Award", date: "May 2024" },
    ],
    socials: [{ platform: "GitHub", handle: "@chenweirobot", url: "#" }, { platform: "Scholar", handle: "Chen Wei", url: "#" }],
  },
  {
    id: "12", rank: 12, avatar: "🌱", name: "Isabelle Dubois", handle: "@isabelle.d",
    country: "France", flag: "🇫🇷", university: "École Normale Supérieure", niScore: 7804, scoreChange: -15,
    categories: ["research", "social"], tags: ["Climate AI", "Sustainability", "Geoscience"],
    bio: "Climate scientist using ML to model sea-level rise and extreme weather events. Science for policy.",
    followers: 7100, following: 198, rankPercentile: "Top 0.28%", joinedDate: "Apr 2024",
    skills: [{ label: "Climate ML", value: 95, color: "#00BE6A" }, { label: "Research", value: 93, color: "#1A56FF" }, { label: "Policy", value: 84, color: "#F5A200" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 93, weight: "25%", description: "", color: "#1A56FF", items: ["PhD ENS Paris", "École Polytechnique Alumni", "Valedictorian"] },
      { id: "research", name: "Research", icon: "🔬", score: 91, weight: "25%", description: "", color: "#00BE6A", items: ["Nature Climate Change", "7 Papers", "102 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 81, weight: "20%", description: "", color: "#9333EA", items: ["Climate Model OSS", "1,800 Contributions"] },
      { id: "creator", name: "Creator", icon: "✨", score: 63, weight: "15%", description: "", color: "#F5A200", items: ["Climate Brief Newsletter", "Le Monde Op-ed"] },
      { id: "social", name: "Social", icon: "🤝", score: 89, weight: "15%", description: "", color: "#FF4500", items: ["IPCC Contributor", "EU Climate Policy Advisor", "Youth Summit Speaker"] },
    ],
    achievements: [
      { id: "a1", icon: "🌱", title: "Nature Climate Change — Lead Author", date: "Sep 2024" },
      { id: "a2", icon: "🌍", title: "IPCC Contributing Author", date: "Mar 2024" },
      { id: "a3", icon: "🏅", title: "French Academy Young Scientist Award", date: "Jun 2024" },
    ],
    socials: [{ platform: "Scholar", handle: "Isabelle Dubois", url: "#" }, { platform: "LinkedIn", handle: "isabelle-dubois-fr", url: "#" }],
  },
  {
    id: "13", rank: 13, avatar: "🎯", name: "Ravi Sharma", handle: "@ravi.s",
    country: "India", flag: "🇮🇳", university: "IIT Delhi", niScore: 7699, scoreChange: 93,
    categories: ["tech", "gaming"], tags: ["Systems", "Compilers", "Performance"],
    bio: "Systems engineer & competitive programmer. Obsessed with performance optimization at the hardware level.",
    followers: 6300, following: 154, rankPercentile: "Top 0.3%", joinedDate: "Feb 2024",
    skills: [{ label: "Systems", value: 98, color: "#1A56FF" }, { label: "Code", value: 96, color: "#9333EA" }, { label: "Perf", value: 94, color: "#FF4500" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 90, weight: "25%", description: "", color: "#1A56FF", items: ["GPA 9.8/10", "IIT Gold Medal", "Institute Rank 1"] },
      { id: "research", name: "Research", icon: "🔬", score: 74, weight: "25%", description: "", color: "#00BE6A", items: ["PLDI 2024 Paper", "28 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 98, weight: "20%", description: "", color: "#9333EA", items: ["Codeforces 3000+", "LLVM Contributor", "3,400 GH Contributions"] },
      { id: "creator", name: "Creator", icon: "✨", score: 68, weight: "15%", description: "", color: "#F5A200", items: ["Systems Blog 8k readers", "YouTube 5k subs"] },
      { id: "social", name: "Social", icon: "🤝", score: 71, weight: "15%", description: "", color: "#FF4500", items: ["CP Club President", "JEE Mentor"] },
    ],
    achievements: [
      { id: "a1", icon: "🥇", title: "IIT Delhi Institute Gold Medal", date: "May 2024" },
      { id: "a2", icon: "⚡", title: "ICPC Asia Pacific — 2nd Place", date: "Dec 2024" },
      { id: "a3", icon: "💻", title: "PLDI 2024 — Student Research Award", date: "Jun 2024" },
    ],
    socials: [{ platform: "GitHub", handle: "@ravisystems", url: "#" }, { platform: "X", handle: "@ravi_systems", url: "#" }],
  },
  {
    id: "14", rank: 14, avatar: "🦾", name: "Liam O'Brien", handle: "@liam.ob",
    country: "Ireland", flag: "🇮🇪", university: "Trinity College Dublin", niScore: 7581, scoreChange: 42,
    categories: ["tech", "social"], tags: ["Accessibility", "Assistive Tech", "HCI"],
    bio: "Assistive technology engineer. Building tools that make computers accessible to people with disabilities.",
    followers: 9200, following: 312, rankPercentile: "Top 0.33%", joinedDate: "Mar 2024",
    skills: [{ label: "A11y", value: 99, color: "#FF4500" }, { label: "Code", value: 90, color: "#1A56FF" }, { label: "UX", value: 86, color: "#F5A200" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 85, weight: "25%", description: "", color: "#1A56FF", items: ["MSc HCI Trinity", "Government Access Award"] },
      { id: "research", name: "Research", icon: "🔬", score: 76, weight: "25%", description: "", color: "#00BE6A", items: ["ASSETS 2024 Paper", "ACM SIGACCESS", "41 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 90, weight: "20%", description: "", color: "#9333EA", items: ["NVDA Contributor", "2,100 Contributions", "A11y Audit Tools"] },
      { id: "creator", name: "Creator", icon: "✨", score: 77, weight: "15%", description: "", color: "#F5A200", items: ["A11y Weekly Newsletter 12k", "Conference Speaker"] },
      { id: "social", name: "Social", icon: "🤝", score: 94, weight: "15%", description: "", color: "#FF4500", items: ["Tech for Disability Lead", "50k Users Impacted", "EU Digital Inclusion Panel"] },
    ],
    achievements: [
      { id: "a1", icon: "🦾", title: "EU Digital Inclusion Award", date: "Nov 2024" },
      { id: "a2", icon: "🏅", title: "ACM ASSETS 2024 Best Paper", date: "Oct 2024" },
      { id: "a3", icon: "♿", title: "Global Accessibility Awareness Day Speaker", date: "May 2024" },
    ],
    socials: [{ platform: "GitHub", handle: "@liama11y", url: "#" }, { platform: "LinkedIn", handle: "liam-obrien-a11y", url: "#" }],
  },
  {
    id: "15", rank: 15, avatar: "🧠", name: "Yuki Tanaka", handle: "@yuki.t",
    country: "Japan", flag: "🇯🇵", university: "Kyoto University", niScore: 7443, scoreChange: 58,
    categories: ["research", "tech"], tags: ["Neuro-AI", "BCI", "Cognitive Science"],
    bio: "Computational neuroscientist building brain-computer interfaces for motor rehabilitation.",
    followers: 5400, following: 167, rankPercentile: "Top 0.35%", joinedDate: "Mar 2024",
    skills: [{ label: "NeuroAI", value: 96, color: "#9333EA" }, { label: "Python", value: 91, color: "#1A56FF" }, { label: "BCI", value: 94, color: "#00BE6A" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 91, weight: "25%", description: "", color: "#1A56FF", items: ["PhD Kyoto", "JST Fellowship", "Top Graduate"] },
      { id: "research", name: "Research", icon: "🔬", score: 89, weight: "25%", description: "", color: "#00BE6A", items: ["Nature Neuroscience", "5 Papers", "88 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 84, weight: "20%", description: "", color: "#9333EA", items: ["MNE-Python Contributor", "BCI Toolbox OSS"] },
      { id: "creator", name: "Creator", icon: "✨", score: 56, weight: "15%", description: "", color: "#F5A200", items: ["Neuro Outreach Blog", "Public Lecture Series"] },
      { id: "social", name: "Social", icon: "🤝", score: 72, weight: "15%", description: "", color: "#FF4500", items: ["Rehab Patient Impact: 200+", "JST Young Scientist Lead"] },
    ],
    achievements: [
      { id: "a1", icon: "🧠", title: "Nature Neuroscience — Motor BCI Study", date: "Jul 2024" },
      { id: "a2", icon: "🏆", title: "NeurIPS 2024 — Best Clinical Paper", date: "Dec 2024" },
      { id: "a3", icon: "🎓", title: "JST PRESTO Fellowship", date: "Apr 2024" },
    ],
    socials: [{ platform: "Scholar", handle: "Yuki Tanaka", url: "#" }, { platform: "GitHub", handle: "@yukibci", url: "#" }],
  },
  {
    id: "16", rank: 16, avatar: "🎬", name: "Fatima Al-Hassan", handle: "@fatima.h",
    country: "UAE", flag: "🇦🇪", university: "NYU Abu Dhabi", niScore: 7322, scoreChange: 129,
    categories: ["creative", "social"], tags: ["Documentary", "AI Ethics", "Media"],
    bio: "Documentary filmmaker & AI ethics researcher. Exploring how technology reshapes society.",
    followers: 24000, following: 642, rankPercentile: "Top 0.38%", joinedDate: "Jan 2024",
    skills: [{ label: "Film", value: 98, color: "#F5A200" }, { label: "Ethics", value: 94, color: "#FF4500" }, { label: "Writing", value: 90, color: "#9333EA" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 84, weight: "25%", description: "", color: "#1A56FF", items: ["MA Film NYU", "Summa Cum Laude", "Fulbright Scholar"] },
      { id: "research", name: "Research", icon: "🔬", score: 73, weight: "25%", description: "", color: "#00BE6A", items: ["AI Ethics Journal Paper", "FAccT 2024", "38 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 58, weight: "20%", description: "", color: "#9333EA", items: ["Data Journalism Tools", "Visualization Projects"] },
      { id: "creator", name: "Creator", icon: "✨", score: 97, weight: "15%", description: "", color: "#F5A200", items: ["Sundance 2024 Selection", "24k Followers", "3 Award-Winning Docs"] },
      { id: "social", name: "Social", icon: "🤝", score: 91, weight: "15%", description: "", color: "#FF4500", items: ["MENA Women in Tech Lead", "UNESCO Media Panel", "Policy Impact"] },
    ],
    achievements: [
      { id: "a1", icon: "🎬", title: "Sundance Film Festival — Official Selection", date: "Jan 2024" },
      { id: "a2", icon: "🌍", title: "UNESCO AI & Media Commission Member", date: "Sep 2024" },
      { id: "a3", icon: "🏅", title: "Fulbright Scholarship", date: "Aug 2023" },
    ],
    socials: [{ platform: "X", handle: "@fatima_films", url: "#" }, { platform: "LinkedIn", handle: "fatima-al-hassan", url: "#" }, { platform: "Instagram", handle: "@fatima.docs", url: "#" }],
  },
  {
    id: "17", rank: 17, avatar: "🔐", name: "Alex Reeves", handle: "@alex.r",
    country: "USA", flag: "🇺🇸", university: "Carnegie Mellon", niScore: 7198, scoreChange: -8,
    categories: ["tech"], tags: ["Security", "Cryptography", "Zero-Knowledge"],
    bio: "Cryptographer & security researcher. Working on zero-knowledge proof systems for privacy-preserving applications.",
    followers: 8700, following: 234, rankPercentile: "Top 0.4%", joinedDate: "Apr 2024",
    skills: [{ label: "Crypto", value: 97, color: "#9333EA" }, { label: "Proofs", value: 96, color: "#1A56FF" }, { label: "Code", value: 91, color: "#00BE6A" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 89, weight: "25%", description: "", color: "#1A56FF", items: ["PhD CMU CyLab", "NSA Scholarship", "Best MS Thesis"] },
      { id: "research", name: "Research", icon: "🔬", score: 87, weight: "25%", description: "", color: "#00BE6A", items: ["IEEE S&P 2024", "CCS Paper", "61 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 91, weight: "20%", description: "", color: "#9333EA", items: ["circom Contributor", "ZK Proof Library", "2,100 Contributions"] },
      { id: "creator", name: "Creator", icon: "✨", score: 63, weight: "15%", description: "", color: "#F5A200", items: ["ZK Monthly Newsletter 9k", "Security Blog"] },
      { id: "social", name: "Social", icon: "🤝", score: 67, weight: "15%", description: "", color: "#FF4500", items: ["CMU Security Seminar Lead", "CTF Team Captain"] },
    ],
    achievements: [
      { id: "a1", icon: "🔐", title: "IEEE S&P 2024 — Distinguished Paper", date: "May 2024" },
      { id: "a2", icon: "🏆", title: "DEF CON CTF — 1st Place Team", date: "Aug 2024" },
      { id: "a3", icon: "🔑", title: "HackTheBox Pro Labs — Top 10 Global", date: "Jan 2024" },
    ],
    socials: [{ platform: "GitHub", handle: "@alexzk", url: "#" }, { platform: "X", handle: "@alex_crypto", url: "#" }],
  },
  {
    id: "18", rank: 18, avatar: "🌿", name: "Kwame Asante", handle: "@kwame.a",
    country: "Ghana", flag: "🇬🇭", university: "University of Ghana", niScore: 7056, scoreChange: 185,
    categories: ["research", "social"], tags: ["AgriTech", "Food Security", "IoT"],
    bio: "Agricultural technologist. Building IoT and AI systems to improve crop yields and food security across West Africa.",
    followers: 11200, following: 445, rankPercentile: "Top 0.42%", joinedDate: "Jan 2024",
    skills: [{ label: "AgriTech", value: 96, color: "#00BE6A" }, { label: "IoT", value: 88, color: "#F5A200" }, { label: "Impact", value: 95, color: "#FF4500" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 82, weight: "25%", description: "", color: "#1A56FF", items: ["MSc Agri-Informatics", "African Union Scholar", "First Class"] },
      { id: "research", name: "Research", icon: "🔬", score: 77, weight: "25%", description: "", color: "#00BE6A", items: ["Nature Food Publication", "FAO Collaboration", "48 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 84, weight: "20%", description: "", color: "#9333EA", items: ["Open Farm OS Contributor", "IoT Sensor Network OSS"] },
      { id: "creator", name: "Creator", icon: "✨", score: 76, weight: "15%", description: "", color: "#F5A200", items: ["AgriTech Africa Podcast 20k", "Forbes Africa Feature"] },
      { id: "social", name: "Social", icon: "🤝", score: 96, weight: "15%", description: "", color: "#FF4500", items: ["10,000 Farmers Impacted", "UN Food System Champion", "West Africa Network Lead"] },
    ],
    achievements: [
      { id: "a1", icon: "🌿", title: "FAO Innovation Award for Food Security", date: "Oct 2024" },
      { id: "a2", icon: "🏆", title: "MIT Solve Challenge — Grand Prize", date: "Jun 2024" },
      { id: "a3", icon: "🌍", title: "UN Food Systems Champion", date: "Sep 2024" },
    ],
    socials: [{ platform: "LinkedIn", handle: "kwame-asante-gh", url: "#" }, { platform: "X", handle: "@kwame_agri", url: "#" }],
  },
  {
    id: "19", rank: 19, avatar: "💡", name: "Mei Lin", handle: "@mei.l",
    country: "Taiwan", flag: "🇹🇼", university: "NTU", niScore: 6934, scoreChange: 66,
    categories: ["tech", "creative"], tags: ["Hardware", "Semiconductors", "PCB Design"],
    bio: "Hardware engineer & chip designer. Optimizing RISC-V processors for edge AI inference.",
    followers: 4800, following: 189, rankPercentile: "Top 0.44%", joinedDate: "May 2024",
    skills: [{ label: "VLSI", value: 97, color: "#1A56FF" }, { label: "RISC-V", value: 94, color: "#9333EA" }, { label: "Verilog", value: 96, color: "#F5A200" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 91, weight: "25%", description: "", color: "#1A56FF", items: ["PhD EE NTU", "TSMC Scholar", "Top 3 Graduate"] },
      { id: "research", name: "Research", icon: "🔬", score: 83, weight: "25%", description: "", color: "#00BE6A", items: ["ISSCC 2024 Paper", "VLSI Symposium", "35 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 89, weight: "20%", description: "", color: "#9333EA", items: ["RISC-V Core Open Source", "Chisel Contributor", "1,700 Contributions"] },
      { id: "creator", name: "Creator", icon: "✨", score: 65, weight: "15%", description: "", color: "#F5A200", items: ["Hardware Design Tutorial Series", "4k YouTube Subs"] },
      { id: "social", name: "Social", icon: "🤝", score: 63, weight: "15%", description: "", color: "#FF4500", items: ["IEEE SSCS Member", "VLSI Workshop Organizer"] },
    ],
    achievements: [
      { id: "a1", icon: "💡", title: "ISSCC 2024 — Best Student Paper Award", date: "Feb 2024" },
      { id: "a2", icon: "🏆", title: "TSMC Scholarship — Hardware Excellence", date: "Sep 2023" },
      { id: "a3", icon: "🔬", title: "VLSI Symposium — Invited Paper", date: "Jun 2024" },
    ],
    socials: [{ platform: "GitHub", handle: "@meilinchip", url: "#" }, { platform: "Scholar", handle: "Mei Lin NTU", url: "#" }],
  },
  {
    id: "20", rank: 20, avatar: "🎤", name: "Jordan Baptiste", handle: "@jordan.b",
    country: "Canada", flag: "🇨🇦", university: "McGill University", niScore: 6821, scoreChange: 204,
    categories: ["creative", "social"], tags: ["Science Communication", "Media", "Podcast"],
    bio: "Science communicator & educator. Making complex science accessible to millions through podcasts and YouTube.",
    followers: 42000, following: 891, rankPercentile: "Top 0.45%", joinedDate: "Jan 2024",
    skills: [{ label: "Comm", value: 99, color: "#F5A200" }, { label: "Science", value: 87, color: "#00BE6A" }, { label: "Media", value: 97, color: "#9333EA" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 79, weight: "25%", description: "", color: "#1A56FF", items: ["MSc Science Communication", "McGill Excellence Award"] },
      { id: "research", name: "Research", icon: "🔬", score: 61, weight: "25%", description: "", color: "#00BE6A", items: ["Sci Comm Journal Paper", "Public Engagement Research"] },
      { id: "code", name: "Code", icon: "💻", score: 56, weight: "20%", description: "", color: "#9333EA", items: ["Data Visualization Projects", "Podcast Platform Tools"] },
      { id: "creator", name: "Creator", icon: "✨", score: 99, weight: "15%", description: "", color: "#F5A200", items: ["42k Followers", "Podcast 2M Downloads", "YouTube 180k Subs", "Best Sci Podcast 2024"] },
      { id: "social", name: "Social", icon: "🤝", score: 93, weight: "15%", description: "", color: "#FF4500", items: ["Science Literacy Advocate", "100 School Programs", "STEM Mentor Network"] },
    ],
    achievements: [
      { id: "a1", icon: "🎤", title: "iTunes Best Science Podcast 2024", date: "Dec 2024" },
      { id: "a2", icon: "📺", title: "YouTube Silver Play Button — 180k subs", date: "Aug 2024" },
      { id: "a3", icon: "🌟", title: "Canadian Science Communicator of the Year", date: "Nov 2024" },
    ],
    socials: [{ platform: "YouTube", handle: "@jordanscience", url: "#" }, { platform: "X", handle: "@jordan_explains", url: "#" }, { platform: "Instagram", handle: "@jordan.science", url: "#" }],
  },
  {
    id: "21", rank: 21, avatar: "🧬", name: "Lena Fischer", handle: "@lena.f",
    country: "Germany", flag: "🇩🇪", university: "ETH Zürich", niScore: 6798, scoreChange: 167,
    categories: ["research", "tech"], tags: ["Quantum Computing", "Physics", "HPC"],
    bio: "Quantum computing researcher at ETH Zürich. Building fault-tolerant qubits and open-source quantum simulation tools.",
    followers: 14200, following: 390, rankPercentile: "Top 0.47%", joinedDate: "Mar 2024",
    skills: [{ label: "Physics", value: 97, color: "#1A56FF" }, { label: "Code", value: 88, color: "#9333EA" }, { label: "Research", value: 93, color: "#00BE6A" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 96, weight: "25%", description: "", color: "#1A56FF", items: ["MSc Physics ETH Zürich", "Quantum Excellence Prize", "Top Graduate 2023"] },
      { id: "research", name: "Research", icon: "🔬", score: 92, weight: "25%", description: "", color: "#00BE6A", items: ["5 Published Papers", "Nature Quantum 2024", "87 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 85, weight: "20%", description: "", color: "#9333EA", items: ["Qiskit Contributor", "Open-source QSim Tool", "1,400 Contributions"] },
      { id: "creator", name: "Creator", icon: "✨", score: 63, weight: "15%", description: "", color: "#F5A200", items: ["Quantum Explainers Blog", "8k Newsletter Subs"] },
      { id: "social", name: "Social", icon: "🤝", score: 70, weight: "15%", description: "", color: "#FF4500", items: ["Women in Quantum Founder", "ETH Physics Tutor"] },
    ],
    achievements: [
      { id: "a1", icon: "⚛️", title: "ETH Zürich Quantum Excellence Prize", date: "Dec 2024" },
      { id: "a2", icon: "📄", title: "Nature Quantum — Invited Paper", date: "Aug 2024" },
      { id: "a3", icon: "🏅", title: "IBM Quantum Network Fellowship", date: "May 2024" },
    ],
    socials: [{ platform: "GitHub", handle: "@lenafischer", url: "#" }, { platform: "Scholar", handle: "Lena Fischer ETH", url: "#" }],
  },
  {
    id: "22", rank: 22, avatar: "🌍", name: "Aisha Nkosi", handle: "@aisha.n",
    country: "South Africa", flag: "🇿🇦", university: "University of Cape Town", niScore: 6744, scoreChange: 211,
    categories: ["tech", "social"], tags: ["Networks", "Systems", "Africa Tech"],
    bio: "Systems engineer building reliable internet infrastructure for underserved communities across sub-Saharan Africa.",
    followers: 18900, following: 504, rankPercentile: "Top 0.48%", joinedDate: "Feb 2024",
    skills: [{ label: "Networks", value: 94, color: "#1A56FF" }, { label: "Systems", value: 90, color: "#9333EA" }, { label: "Impact", value: 97, color: "#FF4500" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 89, weight: "25%", description: "", color: "#1A56FF", items: ["PhD Computer Networks UCT", "African Research Excellence Award"] },
      { id: "research", name: "Research", icon: "🔬", score: 88, weight: "25%", description: "", color: "#00BE6A", items: ["ACM SIGCOMM Best Student Paper", "4 Conference Papers", "62 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 87, weight: "20%", description: "", color: "#9333EA", items: ["AfricaNet OSS Toolkit", "2,100 Contributions"] },
      { id: "creator", name: "Creator", icon: "✨", score: 72, weight: "15%", description: "", color: "#F5A200", items: ["Africa Tech Newsletter 22k", "TEDx Cape Town Talk"] },
      { id: "social", name: "Social", icon: "🤝", score: 96, weight: "15%", description: "", color: "#FF4500", items: ["1M+ users on her network infra", "Girls in Tech Mentor SA"] },
    ],
    achievements: [
      { id: "a1", icon: "🏆", title: "ACM SIGCOMM — Best Student Paper", date: "Sep 2024" },
      { id: "a2", icon: "🌍", title: "African Union Digital Innovation Award", date: "Nov 2024" },
      { id: "a3", icon: "🎤", title: "TEDx Cape Town — Speaker", date: "Oct 2024" },
    ],
    socials: [{ platform: "GitHub", handle: "@aishanko", url: "#" }, { platform: "LinkedIn", handle: "aisha-nkosi", url: "#" }],
  },
  {
    id: "23", rank: 23, avatar: "🎵", name: "Rajan Pillai", handle: "@rajan.p",
    country: "India", flag: "🇮🇳", university: "IISc Bangalore", niScore: 6702, scoreChange: 189,
    categories: ["research", "creative"], tags: ["Audio AI", "Music Tech", "DSP"],
    bio: "Audio AI researcher merging music theory with deep learning. Building systems that compose and understand music.",
    followers: 21300, following: 412, rankPercentile: "Top 0.49%", joinedDate: "Jan 2024",
    skills: [{ label: "Audio AI", value: 96, color: "#9333EA" }, { label: "Research", value: 89, color: "#00BE6A" }, { label: "Music", value: 98, color: "#F5A200" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 92, weight: "25%", description: "", color: "#1A56FF", items: ["PhD Electrical Engineering IISc", "Prime Minister's Research Fellowship"] },
      { id: "research", name: "Research", icon: "🔬", score: 87, weight: "25%", description: "", color: "#00BE6A", items: ["ISMIR 2024 Best Paper", "4 Publications", "53 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 84, weight: "20%", description: "", color: "#9333EA", items: ["AudioCraft Contributor", "OSS Music Gen Model", "1,800 Contributions"] },
      { id: "creator", name: "Creator", icon: "✨", score: 91, weight: "15%", description: "", color: "#F5A200", items: ["Audio AI YouTube 95k", "Music x AI Podcast", "SoundCloud 15k Followers"] },
      { id: "social", name: "Social", icon: "🤝", score: 73, weight: "15%", description: "", color: "#FF4500", items: ["IISc Music Circle Lead", "AI for Musicians Workshop"] },
    ],
    achievements: [
      { id: "a1", icon: "🎵", title: "ISMIR 2024 — Best Paper Award", date: "Nov 2024" },
      { id: "a2", icon: "🏅", title: "Prime Minister's Research Fellowship", date: "Aug 2023" },
      { id: "a3", icon: "📺", title: "YouTube Silver Button — 95k subs", date: "Sep 2024" },
    ],
    socials: [{ platform: "GitHub", handle: "@rajanpillai", url: "#" }, { platform: "YouTube", handle: "@rajanmusic", url: "#" }],
  },
  {
    id: "24", rank: 24, avatar: "🌊", name: "Nadia Petrova", handle: "@nadia.p",
    country: "Russia", flag: "🇷🇺", university: "Moscow State University", niScore: 6658, scoreChange: 93,
    categories: ["research"], tags: ["Climate Science", "Oceanography", "Data Science"],
    bio: "Climate scientist and oceanographer. Using ML to model ocean heat absorption and climate feedback loops.",
    followers: 11700, following: 287, rankPercentile: "Top 0.50%", joinedDate: "Apr 2024",
    skills: [{ label: "Climate", value: 96, color: "#00BE6A" }, { label: "Data Sci", value: 89, color: "#1A56FF" }, { label: "Research", value: 94, color: "#9333EA" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 95, weight: "25%", description: "", color: "#1A56FF", items: ["PhD Oceanography MSU", "Russian Academy of Sciences Scholar"] },
      { id: "research", name: "Research", icon: "🔬", score: 93, weight: "25%", description: "", color: "#00BE6A", items: ["Nature Climate Change 2024", "6 Published Papers", "109 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 82, weight: "20%", description: "", color: "#9333EA", items: ["OceanML Framework OSS", "1,200 Contributions", "Xarray Contributor"] },
      { id: "creator", name: "Creator", icon: "✨", score: 61, weight: "15%", description: "", color: "#F5A200", items: ["Climate Data Substack 12k", "Science Twitter 28k"] },
      { id: "social", name: "Social", icon: "🤝", score: 68, weight: "15%", description: "", color: "#FF4500", items: ["IPCC Contributing Author", "Arctic Research Expedition Lead"] },
    ],
    achievements: [
      { id: "a1", icon: "🌊", title: "Nature Climate Change — Lead Author", date: "Jun 2024" },
      { id: "a2", icon: "🏆", title: "AGU Outstanding Student Award", date: "Dec 2024" },
      { id: "a3", icon: "🌍", title: "IPCC AR7 Contributing Author", date: "Jan 2025" },
    ],
    socials: [{ platform: "Scholar", handle: "Nadia Petrova", url: "#" }, { platform: "X", handle: "@nadia_climate", url: "#" }],
  },
  {
    id: "25", rank: 25, avatar: "💫", name: "Carlos Herrera", handle: "@carlos.h",
    country: "Mexico", flag: "🇲🇽", university: "UNAM", niScore: 6612, scoreChange: 128,
    categories: ["tech", "creative"], tags: ["Open Source", "DevTools", "CLI"],
    bio: "Open-source developer and CLI wizard from Mexico City. Creator of tools with 50k+ GitHub stars across 8 projects.",
    followers: 38200, following: 920, rankPercentile: "Top 0.52%", joinedDate: "Feb 2024",
    skills: [{ label: "Open Source", value: 99, color: "#00BE6A" }, { label: "DevTools", value: 96, color: "#9333EA" }, { label: "Community", value: 91, color: "#FF4500" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 81, weight: "25%", description: "", color: "#1A56FF", items: ["BSc Computer Science UNAM", "UNAM Excellence Award"] },
      { id: "research", name: "Research", icon: "🔬", score: 65, weight: "25%", description: "", color: "#00BE6A", items: ["Developer Survey Papers", "Open Source Research"] },
      { id: "code", name: "Code", icon: "💻", score: 99, weight: "20%", description: "", color: "#9333EA", items: ["50k+ GitHub Stars Total", "8 Popular OSS Projects", "3,900 Contributions"] },
      { id: "creator", name: "Creator", icon: "✨", score: 88, weight: "15%", description: "", color: "#F5A200", items: ["YouTube CLI Tutorials 120k", "Dev.to Top Author", "OSS Newsletter 18k"] },
      { id: "social", name: "Social", icon: "🤝", score: 90, weight: "15%", description: "", color: "#FF4500", items: ["LatAm OSS Community Lead", "Maintainer of 8 repos", "Mentored 30+ contributors"] },
    ],
    achievements: [
      { id: "a1", icon: "⭐", title: "GitHub Star Developer 2024", date: "Mar 2024" },
      { id: "a2", icon: "🏆", title: "50,000 GitHub Stars Milestone", date: "Nov 2024" },
      { id: "a3", icon: "🌎", title: "LatAm Open Source Award 2024", date: "Aug 2024" },
    ],
    socials: [{ platform: "GitHub", handle: "@carlosherrera", url: "#" }, { platform: "X", handle: "@carlos_oss", url: "#" }, { platform: "YouTube", handle: "@carlosdevtools", url: "#" }],
  },
  {
    id: "26", rank: 26, avatar: "🤖", name: "Hana Sato", handle: "@hana.s",
    country: "Japan", flag: "🇯🇵", university: "Kyoto University", niScore: 6571, scoreChange: 204,
    categories: ["research", "tech"], tags: ["Robotics", "Embodied AI", "ROS"],
    bio: "Robotics engineer at Kyoto University. Building embodied AI systems for assistive robotics. Google Brain Resident 2025.",
    followers: 13400, following: 356, rankPercentile: "Top 0.53%", joinedDate: "Mar 2024",
    skills: [{ label: "Robotics", value: 97, color: "#1A56FF" }, { label: "AI", value: 93, color: "#9333EA" }, { label: "Research", value: 90, color: "#00BE6A" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 94, weight: "25%", description: "", color: "#1A56FF", items: ["PhD Robotics Kyoto University", "JSPS Research Fellow", "Best PhD Thesis Award"] },
      { id: "research", name: "Research", icon: "🔬", score: 89, weight: "25%", description: "", color: "#00BE6A", items: ["ICRA 2024 Best Paper", "5 Publications", "74 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 88, weight: "20%", description: "", color: "#9333EA", items: ["ROS 2 Contributor", "AssistBot OSS Framework", "1,650 Contributions"] },
      { id: "creator", name: "Creator", icon: "✨", score: 67, weight: "15%", description: "", color: "#F5A200", items: ["Robotics Demos YouTube 45k", "ROS Tutorial Series"] },
      { id: "social", name: "Social", icon: "🤝", score: 72, weight: "15%", description: "", color: "#FF4500", items: ["IEEE RAS Member", "Kyoto Robotics Lab Lead", "Girls in Robotics Japan"] },
    ],
    achievements: [
      { id: "a1", icon: "🤖", title: "ICRA 2024 — Best Paper Award", date: "May 2024" },
      { id: "a2", icon: "🏅", title: "Google Brain Residency 2025", date: "Jan 2025" },
      { id: "a3", icon: "🎓", title: "JSPS Research Fellowship", date: "Apr 2024" },
    ],
    socials: [{ platform: "GitHub", handle: "@hanasato", url: "#" }, { platform: "Scholar", handle: "Hana Sato Kyoto", url: "#" }],
  },
  {
    id: "27", rank: 27, avatar: "📊", name: "Ibrahim Al-Rashid", handle: "@ibrahim.ar",
    country: "UAE", flag: "🇦🇪", university: "MBZUAI", niScore: 6534, scoreChange: 147,
    categories: ["tech", "research"], tags: ["FinTech", "Quant Finance", "ML"],
    bio: "Quantitative researcher combining ML with financial modelling at MBZUAI. Building open-source tools for accessible quant finance.",
    followers: 16700, following: 441, rankPercentile: "Top 0.54%", joinedDate: "Apr 2024",
    skills: [{ label: "Quant", value: 97, color: "#F5A200" }, { label: "ML", value: 92, color: "#1A56FF" }, { label: "Finance", value: 95, color: "#00BE6A" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 93, weight: "25%", description: "", color: "#1A56FF", items: ["MSc AI & Finance MBZUAI", "UAE AI Excellence Award", "Summa Cum Laude"] },
      { id: "research", name: "Research", icon: "🔬", score: 86, weight: "25%", description: "", color: "#00BE6A", items: ["ICAIF 2024 Best Paper", "3 Published Papers", "41 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 91, weight: "20%", description: "", color: "#9333EA", items: ["QuantML Library OSS", "2,300 Contributions", "Pandas Contributor"] },
      { id: "creator", name: "Creator", icon: "✨", score: 82, weight: "15%", description: "", color: "#F5A200", items: ["Quant Finance Newsletter 25k", "YouTube Trading AI 72k"] },
      { id: "social", name: "Social", icon: "🤝", score: 75, weight: "15%", description: "", color: "#FF4500", items: ["MENA FinTech Community", "CFA Society UAE Speaker"] },
    ],
    achievements: [
      { id: "a1", icon: "💹", title: "ICAIF 2024 — Best Paper on ML Finance", date: "Oct 2024" },
      { id: "a2", icon: "🏆", title: "UAE AI Excellence Award", date: "Dec 2024" },
      { id: "a3", icon: "📈", title: "QuantML Library — 8k GitHub Stars", date: "Sep 2024" },
    ],
    socials: [{ platform: "GitHub", handle: "@ibrahimar", url: "#" }, { platform: "LinkedIn", handle: "ibrahim-al-rashid", url: "#" }, { platform: "X", handle: "@ibrahim_quant", url: "#" }],
  },
  {
    id: "28", rank: 28, avatar: "🎨", name: "Yuki Tanaka", handle: "@yuki.t",
    country: "Japan", flag: "🇯🇵", university: "Tokyo University of the Arts", niScore: 6489, scoreChange: 77,
    categories: ["creative", "tech"], tags: ["Generative Art", "Creative Coding", "p5.js"],
    bio: "Generative artist and creative coder. Blending algorithms with aesthetics to create interactive art installations exhibited globally.",
    followers: 52100, following: 1240, rankPercentile: "Top 0.55%", joinedDate: "Jan 2024",
    skills: [{ label: "Art", value: 99, color: "#F5A200" }, { label: "Code", value: 91, color: "#9333EA" }, { label: "Design", value: 96, color: "#1A56FF" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 87, weight: "25%", description: "", color: "#1A56FF", items: ["MFA Media Art Tokyo", "Ars Electronica Next Scholar"] },
      { id: "research", name: "Research", icon: "🔬", score: 58, weight: "25%", description: "", color: "#00BE6A", items: ["Computational Creativity Papers", "ACM SIGGRAPH Paper 2024"] },
      { id: "code", name: "Code", icon: "💻", score: 88, weight: "20%", description: "", color: "#9333EA", items: ["p5.js Contributor", "ProcessingJP Lead", "1,900 Contributions"] },
      { id: "creator", name: "Creator", icon: "✨", score: 99, weight: "15%", description: "", color: "#F5A200", items: ["52k Instagram Followers", "10 Global Art Installations", "Tokyo & Berlin Exhibitions"] },
      { id: "social", name: "Social", icon: "🤝", score: 79, weight: "15%", description: "", color: "#FF4500", items: ["Creative Coding Japan Community", "Art × Tech Workshop Series"] },
    ],
    achievements: [
      { id: "a1", icon: "🎨", title: "Ars Electronica — Golden Nica Honorary", date: "Sep 2024" },
      { id: "a2", icon: "🖼", title: "Tokyo MoMA Permanent Collection", date: "Jul 2024" },
      { id: "a3", icon: "🏆", title: "ACM SIGGRAPH — Art Show Featured", date: "Aug 2024" },
    ],
    socials: [{ platform: "Instagram", handle: "@yuki.creates", url: "#" }, { platform: "GitHub", handle: "@yukitanaka", url: "#" }],
  },
  {
    id: "29", rank: 29, avatar: "⚡", name: "Tariq Osman", handle: "@tariq.o",
    country: "Sudan", flag: "🇸🇩", university: "University of Khartoum", niScore: 6441, scoreChange: 231,
    categories: ["tech", "social"], tags: ["Energy Tech", "Solar", "Embedded Systems"],
    bio: "Electrical engineer building low-cost solar microgrids for off-grid communities in East Africa. IEEE Young Engineer of the Year.",
    followers: 19800, following: 567, rankPercentile: "Top 0.56%", joinedDate: "Mar 2024",
    skills: [{ label: "Energy", value: 97, color: "#F5A200" }, { label: "Embedded", value: 91, color: "#1A56FF" }, { label: "Impact", value: 99, color: "#FF4500" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 88, weight: "25%", description: "", color: "#1A56FF", items: ["PhD EE University of Khartoum", "Fulbright Scholar", "IEEE Africa Fellowship"] },
      { id: "research", name: "Research", icon: "🔬", score: 83, weight: "25%", description: "", color: "#00BE6A", items: ["IEEE Transactions on Energy Paper", "3 Publications", "38 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 84, weight: "20%", description: "", color: "#9333EA", items: ["SolarGrid OSS Firmware", "ESP32 Libraries", "1,300 Contributions"] },
      { id: "creator", name: "Creator", icon: "✨", score: 71, weight: "15%", description: "", color: "#F5A200", items: ["Solar Energy YouTube 38k", "Engineering for Africa Newsletter"] },
      { id: "social", name: "Social", icon: "🤝", score: 98, weight: "15%", description: "", color: "#FF4500", items: ["50,000 people with power access", "IEEE YP Sudan Chapter Chair", "UN Energy Advisor"] },
    ],
    achievements: [
      { id: "a1", icon: "⚡", title: "IEEE Young Engineer of the Year 2024", date: "Nov 2024" },
      { id: "a2", icon: "🌍", title: "50k People Given Electricity Access", date: "Oct 2024" },
      { id: "a3", icon: "🏅", title: "Fulbright Scholar 2023", date: "Sep 2023" },
    ],
    socials: [{ platform: "LinkedIn", handle: "tariq-osman", url: "#" }, { platform: "GitHub", handle: "@tariqenergy", url: "#" }],
  },
  {
    id: "30", rank: 30, avatar: "🔐", name: "Mei Chen", handle: "@mei.c",
    country: "Taiwan", flag: "🇹🇼", university: "National Taiwan University", niScore: 6398, scoreChange: 156,
    categories: ["tech", "research"], tags: ["Cryptography", "Zero Knowledge", "Blockchain"],
    bio: "Cryptography researcher specialising in zero-knowledge proofs and post-quantum security. Co-author of a widely-used ZK library.",
    followers: 24600, following: 618, rankPercentile: "Top 0.58%", joinedDate: "Feb 2024",
    skills: [{ label: "Crypto", value: 98, color: "#9333EA" }, { label: "ZK", value: 95, color: "#1A56FF" }, { label: "Research", value: 92, color: "#00BE6A" }],
    pillars: [
      { id: "academic", name: "Academic", icon: "🎓", score: 93, weight: "25%", description: "", color: "#1A56FF", items: ["PhD Cryptography NTU", "MOST Fellowship", "Best PhD Dissertation NTU 2024"] },
      { id: "research", name: "Research", icon: "🔬", score: 91, weight: "25%", description: "", color: "#00BE6A", items: ["CCS 2024 Best Paper", "6 Publications", "98 Citations"] },
      { id: "code", name: "Code", icon: "💻", score: 93, weight: "20%", description: "", color: "#9333EA", items: ["zkLib Co-author (12k Stars)", "Halo2 Contributor", "2,200 Contributions"] },
      { id: "creator", name: "Creator", icon: "✨", score: 74, weight: "15%", description: "", color: "#F5A200", items: ["ZK Proofs Explained Blog", "Cryptography YouTube 41k"] },
      { id: "social", name: "Social", icon: "🤝", score: 78, weight: "15%", description: "", color: "#FF4500", items: ["ZK Research Community Lead", "IEEE Security & Privacy Reviewer"] },
    ],
    achievements: [
      { id: "a1", icon: "🔐", title: "ACM CCS 2024 — Best Paper Award", date: "Nov 2024" },
      { id: "a2", icon: "⭐", title: "zkLib — 12,000 GitHub Stars", date: "Dec 2024" },
      { id: "a3", icon: "🏆", title: "Best PhD Dissertation — NTU 2024", date: "Jun 2024" },
    ],
    socials: [{ platform: "GitHub", handle: "@meichen", url: "#" }, { platform: "Scholar", handle: "Mei Chen NTU", url: "#" }, { platform: "X", handle: "@mei_zk", url: "#" }],
  },
];

export const TICKER_ITEMS = [
  { text: "Aryan Kapoor climbed +142 pts this week", change: "+142" },
  { text: "Amara Osei trending in Creative category", change: "+201" },
  { text: "New verified: Sofia Martínez · MIT", change: "✓" },
  { text: "Marcus Chen crossed 8,700 NI Score", change: "+118" },
  { text: "Noah Okafor +244 · fastest riser this month", change: "+244" },
  { text: "2,847 new verifications this month", change: "🔥" },
  { text: "Leaderboard update: 1,284 rank changes today", change: "↑" },
  { text: "Priya Nair — IEEE Best Paper Award verified", change: "✓" },
  { text: "Kenji Nakamura: ICPC World Finals #2 confirmed", change: "✓" },
  { text: "Jordan Baptiste hits 2M podcast downloads", change: "🎤" },
  { text: "Zara Ahmed — Spotify AI Lab Fellowship", change: "✓" },
  { text: "Kwame Asante: 10,000 farmers impacted", change: "🌍" },
  { text: "Aisha Nkosi — ACM SIGCOMM Best Student Paper", change: "✓" },
  { text: "Rajan Pillai climbed +189 pts · top mover", change: "+189" },
  { text: "Lena Fischer — ETH Zurich Quantum Prize", change: "✓" },
  { text: "Nadia Petrova — Nature Climate Change paper", change: "✓" },
  { text: "Carlos Herrera hits 50k GitHub stars", change: "⭐" },
  { text: "Hana Sato — Google Brain Residency confirmed", change: "✓" },
];
